@echo off
echo Starting Anesthetist Service Tracker...
echo.
echo Starting Backend Server...
start cmd /k "cd backend && pip install -r requirements.txt && python app.py"

echo Waiting for backend to start...
timeout /t 5 /nobreak > nul

echo Starting Frontend Development Server...
start cmd /k "cd frontend && npm install && npm start"

echo.
echo Both servers are starting...
echo Backend will be available at: http://localhost:8000
echo Frontend will be available at: http://localhost:3000
echo.
echo Press any key to exit...
pause > nul